"""Install the canonical skill and its agents into every supported coding host.

One source of truth (``~/.ai/skills/android-workflow``) is rendered into each host's own format:
Claude Code, Cursor and Gemini CLI read Markdown agents with YAML frontmatter; Codex reads TOML
custom agents. Hosts without named subagents fall back to the role files shipped in the skill.
"""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path
from typing import Any

SKILL_NAME = "android-workflow"

USER_SKILL_DIRS = (
    Path(".cursor") / "skills" / SKILL_NAME,
    Path(".claude") / "skills" / SKILL_NAME,
    Path(".agents") / "skills" / SKILL_NAME,
    Path(".gemini") / "skills" / SKILL_NAME,
    Path(".codex") / "skills" / SKILL_NAME,
)

PROJECT_SKILL_DIRS = (
    Path(".cursor") / "skills" / SKILL_NAME,
    Path(".claude") / "skills" / SKILL_NAME,
    Path(".agents") / "skills" / SKILL_NAME,
    Path(".gemini") / "skills" / SKILL_NAME,
)

AGENT_PREFIX = "aw-"

# Role tier -> per-host setting. Claude Code picks a model; Codex picks reasoning effort.
# Cursor and Gemini CLI inherit the session model.
CLAUDE_MODELS = {"strong": "opus", "standard": "sonnet", "fast": "haiku"}
CODEX_EFFORT = {"strong": "high", "standard": "medium", "fast": "low"}

GENERATED_NOTE = (
    "<!-- Generated by `android-workflow install-host` from {source}. "
    "Edit the source and re-run install-host. -->"
)

AGENTS_SNIPPET = """
## Android Workflow

Use `/android-workflow <ticket-id> <title>` (or `$android-workflow` on Codex).
The coding agent is the **orchestrator** of the aw-* agents: the run is not done until the
Android app has a verified source diff and, unless a `--no-*` flag says otherwise, an open PR.
Follow `.agents/skills/android-workflow/SKILL.md` or the equivalent Cursor, Claude Code,
Codex or Gemini skill in this repo.
"""


def toolkit_root() -> Path:
    return Path(__file__).resolve().parent.parent


def canonical_skill_dir(home: Path | None = None) -> Path:
    """The skill beside this toolkit in ~/.ai (`~/.ai/tools/android-workflow` → `~/.ai/skills`)."""
    user_copy = (home or Path.home()) / ".ai" / "skills" / SKILL_NAME
    if (user_copy / "SKILL.md").is_file():
        return user_copy
    return toolkit_root().parents[1] / "skills" / SKILL_NAME


def parse_role(path: Path) -> tuple[dict[str, str], str]:
    """Split a role file into flat frontmatter (JSON-quoted or bare values) and its body."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"role file has no frontmatter: {path}")
    header, body = text[4:].split("\n---\n", 1)
    meta: dict[str, str] = {}
    for line in header.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        meta[key.strip()] = json.loads(value) if value.startswith('"') else value
    for key in ("name", "description", "tier"):
        if not meta.get(key):
            raise ValueError(f"role file {path} is missing `{key}`")
    return meta, body.lstrip("\n")


def role_files(skill_dir: Path) -> list[Path]:
    return sorted((skill_dir / "agents").glob(f"{AGENT_PREFIX}*.md"))


def markdown_agent(meta: dict[str, str], body: str, source: Path, extra: dict[str, str]) -> str:
    lines = ["---", f"name: {meta['name']}", f"description: {json.dumps(meta['description'])}"]
    lines.extend(f"{key}: {value}" for key, value in extra.items())
    lines.extend(["---", "", GENERATED_NOTE.format(source=source), "", body.rstrip(), ""])
    return "\n".join(lines)


def codex_agent(meta: dict[str, str], body: str, source: Path) -> str:
    instructions = f"{GENERATED_NOTE.format(source=source)}\n\n{body.rstrip()}\n"
    if "'''" in instructions:
        raise ValueError(f"role body cannot contain a TOML literal delimiter: {source}")
    return (
        f"name = {json.dumps(meta['name'])}\n"
        f"description = {json.dumps(meta['description'])}\n"
        f"model_reasoning_effort = {json.dumps(CODEX_EFFORT[meta['tier']])}\n"
        f"developer_instructions = '''\n{instructions}'''\n"
    )


def render_agents(skill_dir: Path) -> dict[str, dict[str, str]]:
    """Return {host: {filename: content}} for every aw-* role in the skill."""
    rendered: dict[str, dict[str, str]] = {"claude": {}, "cursor": {}, "gemini": {}, "codex": {}}
    for path in role_files(skill_dir):
        meta, body = parse_role(path)
        name = meta["name"]
        claude = {"model": CLAUDE_MODELS[meta["tier"]]}
        if meta.get("tools"):
            claude = {"tools": meta["tools"], **claude}
        rendered["claude"][f"{name}.md"] = markdown_agent(meta, body, path, claude)
        rendered["cursor"][f"{name}.md"] = markdown_agent(meta, body, path, {})
        rendered["gemini"][f"{name}.md"] = markdown_agent(meta, body, path, {"kind": "local"})
        rendered["codex"][f"{name}.toml"] = codex_agent(meta, body, path)
    return rendered


def write_agents(base: Path, skill_dir: Path) -> list[str]:
    """Write every host's agent registrations under base (home or project); returns paths."""
    written: list[str] = []
    for host, files in render_agents(skill_dir).items():
        folder = base / f".{host}" / "agents"
        folder.mkdir(parents=True, exist_ok=True)
        for filename, content in files.items():
            path = folder / filename
            path.write_text(content, encoding="utf-8")
            written.append(str(path))
        # A role removed from the skill leaves its old registration behind; drop only files we generated.
        for stale in folder.glob(f"{AGENT_PREFIX}*"):
            if stale.name not in files and stale.is_file() and "Generated by `android-workflow install-host`" in stale.read_text(
                encoding="utf-8", errors="ignore"
            ):
                stale.unlink()
                written.append(f"removed {stale}")
    return written


def copy_skill(source: Path, destination: Path, python_executable: str, root: Path) -> None:
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination, dirs_exist_ok=False)
    (destination / "toolkit-root.txt").write_text(str(root) + "\n", encoding="utf-8")
    (destination / "python.txt").write_text(python_executable + "\n", encoding="utf-8")


def host_notes(home: Path) -> list[str]:
    """Settings a host needs before it can spawn the aw-* agents; install-host never edits them."""
    notes: list[str] = []
    codex_config = home / ".codex" / "config.toml"
    if codex_config.is_file():
        text = codex_config.read_text(encoding="utf-8")
        try:
            import tomllib

            enabled = tomllib.loads(text).get("features", {}).get("multi_agent_v2") is True
        except ImportError:  # Python < 3.11: read the one key we need
            section = re.search(r"^\[features\]\s*$(.*?)(?=^\[|\Z)", text, re.M | re.S)
            enabled = bool(section and re.search(r"^\s*multi_agent_v2\s*=\s*true\b", section.group(1), re.M))
        except ValueError:
            enabled = False
        if not enabled:
            notes.append(
                "Codex: add `multi_agent_v2 = true` under [features] in ~/.codex/config.toml; "
                "without it Codex has no spawn_agent tool and runs the roles inline."
            )
    return notes


def remove_shadowing_claude_command(base: Path) -> str | None:
    """A `.claude/commands/<name>.md` shadows the skill of the same name in Claude Code, so a stale
    one silently replaces the workflow. Skills are already invocable as `/android-workflow`."""
    path = base / ".claude" / "commands" / f"{SKILL_NAME}.md"
    if path.is_file():
        path.unlink()
        return str(path)
    return None


def merge_agents_md(project: Path) -> Path:
    path = project / "AGENTS.md"
    marker = "## Android Workflow"
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    if marker not in existing:
        prefix = existing.rstrip() + "\n\n" if existing.strip() else ""
        path.write_text(prefix + AGENTS_SNIPPET.lstrip(), encoding="utf-8")
    return path


def install_host(
    *,
    user: bool,
    target: Path | None,
    home: Path,
    python_executable: str,
) -> dict[str, Any]:
    source = canonical_skill_dir(home)
    if not (source / "SKILL.md").is_file():
        raise FileNotFoundError(f"canonical skill missing: {source / 'SKILL.md'}")
    root = toolkit_root()
    installed: list[str] = []
    skipped: list[dict[str, str]] = []

    def try_copy(destination: Path) -> None:
        try:
            copy_skill(source, destination, python_executable, root)
            installed.append(str(destination))
        except OSError as error:
            skipped.append({"path": str(destination), "error": str(error)})

    def try_agents(base: Path) -> None:
        try:
            installed.extend(write_agents(base, source))
        except (OSError, ValueError) as error:
            skipped.append({"path": str(base), "error": f"agents: {error}"})

    if user:
        for relative in USER_SKILL_DIRS:
            try_copy(home / relative)
        try_agents(home)
        if removed := remove_shadowing_claude_command(home):
            installed.append(f"removed {removed}")
    if target:
        target = target.resolve()
        for relative in PROJECT_SKILL_DIRS:
            try_copy(target / relative)
        try_agents(target)
        if removed := remove_shadowing_claude_command(target):
            installed.append(f"removed {removed}")
        try:
            merge_agents_md(target)
            installed.append(str(target / "AGENTS.md"))
        except OSError as error:
            skipped.append({"path": str(target / "AGENTS.md"), "error": str(error)})
    if not user and not target:
        raise ValueError("pass --user and/or --target")
    if not installed:
        raise OSError("no skill destination could be written: " + json_errors(skipped))
    return {
        "installed": installed,
        "skipped": skipped,
        "notes": host_notes(home) if user else [],
        "skill_source": str(source),
        "toolkit_root": str(root),
        "python": python_executable,
    }


def json_errors(skipped: list[dict[str, str]]) -> str:
    return "; ".join(f"{item['path']}: {item['error']}" for item in skipped)
